name: modspectra

channels:
    - astropy

dependencies:
    - python=>3.6
    - sphinx-astropy
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - numexpr
    - dask
    - regions
#   - spectral-cube
#   - pip:
#       - dependency_from_pip
    - spectral-cube
