name: modspectra

channels:
    - astropy

dependencies:
    - python=3.5
    - sphinx-astropy
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - numexpr
    - spectral-cube
#   - pip:
#       - dependency_from_pip
